# Generated by Django 4.1.7 on 2023-02-21 10:29

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [

    ]
