# Generated by Django 4.1.7 on 2023-02-23 19:20

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_imageupload_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=500, upload_to=base.models.upload_location)),
                ('type', models.CharField(choices=[('image_chart', 'image_chart'), ('image_result', 'image_result')], max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
